import NavBar from "@/components/NavBar"
import "./globals.css"

export const metadata = {
	title: "Innovation",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className='bg-slate-100 text-slate-950'>
				<NavBar />
				{children}
			</body>
		</html>
	)
}
